Добавлены тестовые функции по добавлению контактов, получению id полей номера и email
- Функция по добавлению контактов почти готова. Нужно настроить данные, получаемые из иных функций.
  А именно функций, возвращающих field_code email'а и телефона

- Сами функции получения field кодов email'а и телефона

- Присутствует один баг: при запуске выводиться ошибка в следующих строках:
106            response = requests.get("https://{}.amocrm.ru{}".format(
107                subdomain, kwargs.get("endpoint")), headers=headers).json()
  Ошибка:
  	Exception has occurred: ConnectionError
	HTTPSConnectionPool(host='gellyhoup.amocrm.ruapi', port=443): Max retries exceeded with url: /v4/contacts/custom_fields (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002ED9FB4D3D0>: Failed to resolve 'gellyhoup.amocrm.ruapi' ([Errno 11001] getaddrinfo failed)"))
	socket.gaierror: [Errno 11001] getaddrinfo failed

	The above exception was the direct cause of the following exception:

	urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002ED9FB4D3D0>: Failed to resolve 'gellyhoup.amocrm.ruapi' ([Errno 11001] getaddrinfo failed)

	The above exception was the direct cause of the following exception:

	urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gellyhoup.amocrm.ruapi', port=443): Max retries exceeded with url: /v4/contacts/custom_fields (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002ED9FB4D3D0>: Failed to resolve 'gellyhoup.amocrm.ruapi' ([Errno 11001] getaddrinfo failed)"))

	During handling of the above exception, another exception occurred:

	  File "C:\Users\kazim\OneDrive\Документы\vs_code_pj\test\urls.py", line 106, in _base_request
	    response = requests.get("https://{}.amocrm.ru{}".format(
	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\kazim\OneDrive\Документы\vs_code_pj\test\urls.py", line 135, in get_custom_field
	    return self._base_request(endpoint="api/v4/contacts/custom_fields", type="get")
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\kazim\OneDrive\Документы\vs_code_pj\test\test_crm.py", line 6, in <module>
	    print(amorcm_object.get_custom_field())
	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gellyhoup.amocrm.ruapi', port=443): Max retries exceeded with url: /v4/contacts/custom_fields (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002ED9FB4D3D0>: Failed to resolve 'gellyhoup.amocrm.ruapi' ([Errno 11001] getaddrinfo failed)"))

	Такая же ошибка присутствовала в первой версии проекта в мастер ветке ещё до добавления репозитория в github